# ─ p10k Theme — WezTerm + Catppuccin ─

# Repertory
typeset -g POWERLEVEL9K_DIR_FOREGROUND=189
typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND=111
typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND=102

# Git — normal
typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND=232

# Git — modified
typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=232

# Git — untracked
typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=232

# Statut
typeset -g POWERLEVEL9K_STATUS_OK=false
typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND=232

# Runtime
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=210

# Hour
typeset -g POWERLEVEL9K_TIME_FOREGROUND=111

# Virtualenv
typeset -g POWERLEVEL9K_VIRTUALENV_FOREGROUND=116
